"""
Model evaluation across v1, v2a, v2b, v3.

Reads claims_all.parquet (generated by run.py) and evaluates each model version on
its OOT holdout window using biased observed labels (SFP-contaminated — as in production).

Two metrics reported per version:
  1. Precision / Recall at that version's actually-applied tuned threshold τ_v (applied_tau)
  2. Threshold required to hit precision >= 0.985 on this OOT window, and resulting recall

These labels are SFP-contaminated, so contaminated precision can look stable/high while the
TRUE (oracle) precision degrades. The true-vs-contaminated gap is measured against
garage_outcome in the synthetic DGP oracle check (verify_sfp_oracle.py) / Build 03.
"""

import pandas as pd
import numpy as np
from pathlib import Path
from sklearn.metrics import precision_score, recall_score, roc_auc_score, precision_recall_curve

from generate.config import TARGET_PRECISION
from generate.logger import get_logger

PARQUET_DIR = Path(__file__).parent / "generate" / "parquet"

log = get_logger(__name__)

# OOT holdout windows per model version (matches training split logic in model.py).
# All ML-era versions (v2a/v2b/v3a/v3b) share the 2024-05..10 window: ML train cutoffs are
# aligned at 2024-04-30, so this window is out-of-time and leakage-free for all of them at
# once — the common-window precondition for a valid cross-version comparison (problem.md
# §2.5 #9). v1 sits in its own pre-ML era (2021) and is not row-comparable to the others.
OOT_WINDOWS = {
    "v1":  ("2021-05-01", "2021-10-31"),
    "v2a": ("2024-05-01", "2024-10-31"),
    "v2b": ("2024-05-01", "2024-10-31"),
    "v3a": ("2024-05-01", "2024-10-31"),
    "v3b": ("2024-05-01", "2024-10-31"),
}

# (score_col, label_col) per version
# label_col is the biased observed outcome available at that model's deployment time
# (each version's own training label — v3a learns from v2a's log, v3b from v2b's log).
VERSION_COLS = {
    "v1":  ("model_v1_score",  "pre_ml_label"),
    "v2a": ("model_v2a_score", "model_v1_observed_outcome"),
    "v2b": ("model_v2b_score", "model_v1_observed_outcome"),
    "v3a": ("model_v3a_score", "model_v2a_observed_outcome"),
    "v3b": ("model_v3b_score", "model_v2b_observed_outcome"),
}


def find_precision_threshold(
    y_true: np.ndarray,
    y_score: np.ndarray,
    target: float = TARGET_PRECISION,
) -> tuple[float | None, float | None, float | None]:
    """
    Return (threshold, precision, recall) at the lowest threshold
    that first achieves target precision.

    precision_recall_curve returns arrays sorted by decreasing threshold,
    so the first index where precision >= target is the most permissive
    (lowest) threshold that still hits the target.
    """
    prec, rec, thresholds = precision_recall_curve(y_true, y_score)
    # prec and rec have one extra element at the end (prec[-1]=1, rec[-1]=0, no threshold)
    for p, r, t in zip(prec, rec, thresholds):
        if p >= target:
            return float(t), float(p), float(r)
    return None, None, None


def evaluate_version(
    df: pd.DataFrame,
    version: str,
) -> dict | None:
    score_col, label_col = VERSION_COLS[version]
    decision_col         = f"model_{version}_decision"
    oot_start, oot_end   = OOT_WINDOWS[version]

    if score_col not in df.columns or label_col not in df.columns:
        log.warning(f"[{version}] skipped — {score_col!r} or {label_col!r} not in dataset")
        return None

    dates    = pd.to_datetime(df["claim_date"])
    oot_mask = (dates >= oot_start) & (dates <= oot_end) & df[label_col].notna()
    sub      = df[oot_mask]

    if len(sub) == 0:
        log.warning(f"[{version}] skipped — no rows in OOT window {oot_start} to {oot_end}")
        return None

    y_true  = sub[label_col].astype(int).values
    y_score = sub[score_col].values

    # Metrics at the ACTUAL applied policy: read the version's decision column, which was
    # generated with that version's tuned τ_v (not a hardcoded 0.872). The applied τ_v is
    # recovered as the lowest score among scrapped rows, for transparency.
    y_dec        = sub[decision_col].astype(int).values
    applied      = {
        "precision":  float(precision_score(y_true, y_dec, zero_division=0)),
        "recall":     float(recall_score(y_true, y_dec, zero_division=0)),
        "scrap_rate": float(y_dec.mean()),
    }
    applied_tau  = float(y_score[y_dec == 1].min()) if y_dec.sum() else float("nan")

    t_opt, p_opt, r_opt  = find_precision_threshold(y_true, y_score, TARGET_PRECISION)
    auc = (
        float(roc_auc_score(y_true, y_score))
        if len(np.unique(y_true)) > 1 else float("nan")
    )

    return {
        "version":              version,
        "oot_rows":             len(sub),
        "label_col":            label_col,
        "auc":                  round(auc, 4),
        "applied_tau":          round(applied_tau, 4),
        "precision_at_applied": round(applied["precision"], 4),
        "recall_at_applied":    round(applied["recall"], 4),
        "scrap_rate_at_applied":round(applied["scrap_rate"], 4),
        "threshold_for_0985":   round(t_opt, 4) if t_opt else None,
        "precision_at_0985":    round(p_opt, 4) if p_opt else None,
        "recall_at_0985":       round(r_opt, 4) if r_opt else None,
    }


def main() -> None:
    claims_all_path = PARQUET_DIR / "claims_all.parquet"
    if not claims_all_path.exists():
        raise FileNotFoundError(
            f"{claims_all_path} not found. Run `python run.py` first to generate claims_all.parquet."
        )

    df   = pd.read_parquet(claims_all_path)
    rows = [evaluate_version(df, v) for v in VERSION_COLS]
    rows = [r for r in rows if r is not None]

    if not rows:
        log.warning("no versions could be evaluated")
        return

    summary = pd.DataFrame(rows).set_index("version")

    log.info("=== Model Evaluation (biased OOT, SFP-contaminated labels) ===")
    log.info("\n" + summary.to_string())
    log.info(
        f"'_at_applied' = metrics at each version's actually-applied tuned τ_v "
        f"(applied_tau); '_at_0985' = threshold re-tuned to precision>={TARGET_PRECISION} "
        f"on this OOT window. NOTE: these labels are SFP-contaminated, so a stable/high "
        f"contaminated precision can still hide degrading TRUE (oracle) precision — the "
        f"latter is measured only in the synthetic DGP oracle check / Build 03."
    )

    out_path = PARQUET_DIR.parent / "csv" / "model_evaluation.csv"
    summary.to_csv(out_path)
    log.info(f"saved model_evaluation.csv → {out_path}")


if __name__ == "__main__":
    main()
